import * as React from "react";
import { useState } from "react";
import { css } from "@emotion/react";
import { Box, TextField, IconButton, Typography } from "@mui/material";
import ContentPasteIcon from "@mui/icons-material/ContentPaste";
import OpenInNewIcon from "@mui/icons-material/OpenInNew";
import InfoOutlinedIcon from "@mui/icons-material/InfoOutlined";
import { BloomTooltip } from "../BloomToolTip";
import { getAsync, post } from "../../utils/bloomApi";
import { headingStyle } from "./sharedStyles";

const URLEditorComponent: React.FunctionComponent<{
    currentURL: string;
    onChange: (url: string) => void;
}> = (props) => {
    const [url, setURL] = useState(props.currentURL);

    React.useEffect(() => {
        setURL(props.currentURL);
    }, [props.currentURL]);

    const isBookPageURL = (urlString: string) => {
        return urlString.startsWith("/book") || urlString.startsWith("#");
    };

    const handleURLChange = (newURL: string) => {
        setURL(newURL);
        props.onChange(newURL);
    };

    const handlePaste = async () => {
        try {
            const response = await getAsync("common/clipboardText");
            const clipboardText =
                typeof response.data === "string"
                    ? response.data
                    : (response.data?.data ?? "");

            if (!clipboardText) {
                return;
            }

            // If the current URL still reflects a book/page link, replace it entirely
            if (isBookPageURL(url)) {
                setURL(clipboardText);
                props.onChange(clipboardText);
                return;
            }

            handleURLChange(clipboardText);
        } catch (error) {
            console.error("Failed to get clipboard text:", error);
        }
    };

    const handleOpenInBrowser = () => {
        const normalizedUrl = url.trim();
        if (!normalizedUrl || normalizedUrl.startsWith("/book")) {
            return;
        }

        // Use the Bloom API to open the URL in the default browser
        post(`common/openUrl?url=${encodeURIComponent(normalizedUrl)}`);
    };

    const normalizedUrl = url.trim();
    const isOpenButtonDisabled =
        normalizedUrl.length === 0 || normalizedUrl.startsWith("/book");

    return (
        <Box
            css={css`
                display: flex;
                flex-direction: column;
                margin: 0;
            `}
        >
            <Typography css={headingStyle}>
                URL
                <BloomTooltip tip="The URL can be a website or one generated by selecting a book and/or page above">
                    <InfoOutlinedIcon
                        css={css`
                            font-size: 18px;
                            color: #666;
                            cursor: help;
                        `}
                    />
                </BloomTooltip>
            </Typography>
            <Box
                css={css`
                    display: flex;
                    align-items: center;
                    gap: 8px;
                `}
            >
                <TextField
                    fullWidth
                    size="small"
                    value={url}
                    onChange={(e) => handleURLChange(e.target.value)}
                    placeholder="Paste or enter a URL"
                    variant="outlined"
                    css={css`
                        flex: 1;
                    `}
                    data-testid="url-input"
                />
                <BloomTooltip tip="Paste from clipboard">
                    <IconButton
                        onClick={handlePaste}
                        size="small"
                        css={css`
                            color: #1976d2;
                        `}
                        data-testid="paste-button"
                    >
                        <ContentPasteIcon />
                    </IconButton>
                </BloomTooltip>
                <BloomTooltip tip="Open in browser">
                    <IconButton
                        onClick={handleOpenInBrowser}
                        size="small"
                        disabled={isOpenButtonDisabled}
                        css={css`
                            color: #1976d2;
                            &:disabled {
                                color: rgba(0, 0, 0, 0.26);
                            }
                        `}
                        data-testid="open-button"
                    >
                        <OpenInNewIcon />
                    </IconButton>
                </BloomTooltip>
            </Box>
        </Box>
    );
};

export const URLEditor = React.memo(
    URLEditorComponent,
    (prevProps, nextProps) => {
        // Only re-render if currentURL or onChange changes
        return (
            prevProps.currentURL === nextProps.currentURL &&
            prevProps.onChange === nextProps.onChange
        );
    },
);
