import * as React from "react";
import { useState } from "react";
import { css } from "@emotion/react";
import {
    Box,
    TextField,
    IconButton,
    Typography,
    Menu,
    MenuItem,
} from "@mui/material";
import ContentPasteIcon from "@mui/icons-material/ContentPaste";
import OpenInNewIcon from "@mui/icons-material/OpenInNew";
import InfoOutlinedIcon from "@mui/icons-material/InfoOutlined";
import MoreHorizIcon from "@mui/icons-material/MoreHoriz";
import { BloomTooltip } from "../BloomToolTip";
import { getAsync, post } from "../../utils/bloomApi";
import { headingStyle } from "./sharedStyles";
import { kBloomBlue } from "../../bloomMaterialUITheme";
import { useL10n } from "../l10nHooks";

// this shows a text field for editing the URL directly, with buttons for paste, open in browser, and a menu for "back"
export const URLEditor: React.FunctionComponent<{
    currentURL: string;
    onChange: (url: string) => void;
}> = (props) => {
    const [url, setURL] = useState(props.currentURL);
    const [moreMenuAnchor, setMoreMenuAnchor] = useState<null | HTMLElement>(
        null,
    );
    // Sync local state with prop changes (e.g., when user selects a book/page).
    // Local state is needed so the input can be edited without triggering onChange on every keystroke.
    React.useEffect(() => {
        setURL(props.currentURL);
    }, [props.currentURL]);

    const urlHeading = useL10n("URL", "LinkTargetChooser.URLSection.Heading");
    const urlTooltip = useL10n(
        "The URL can be a website or one generated by selecting a book and/or page above",
        "LinkTargetChooser.URLSection.InfoIcon.Tooltip",
    );
    const placeholderText = useL10n(
        "Paste or enter a URL",
        "LinkTargetChooser.URLSection.Input.Placeholder",
    );
    const optionsButtonLabel = useL10n(
        "More options",
        "LinkTargetChooser.URLSection.OptionsButton.Label",
    );
    const backMenuTitle = useL10n(
        "Go back in link history",
        "LinkTargetChooser.URLSection.OptionsMenu.Back.Tooltip",
    );
    const backMenuLabel = useL10n(
        "Back",
        "LinkTargetChooser.URLSection.OptionsMenu.Back.Label",
    );
    const pasteTooltip = useL10n(
        "Paste from clipboard",
        "LinkTargetChooser.URLSection.PasteButton.Tooltip",
    );
    const openInBrowserTooltip = useL10n(
        "Open in browser",
        "LinkTargetChooser.URLSection.OpenButton.Tooltip",
    );

    const handleURLChange = (newURL: string) => {
        setURL(newURL);
        props.onChange(newURL);
    };
    const handleMoreMenuClick = (
        event: React.MouseEvent<HTMLButtonElement>,
    ) => {
        setMoreMenuAnchor(event.currentTarget);
    };

    const handleMoreMenuClose = () => {
        setMoreMenuAnchor(null);
    };

    const handleBackMenuItemClick = () => {
        handleURLChange("/back");
        handleMoreMenuClose();
    };

    const handlePaste = async () => {
        try {
            const response = await getAsync("common/clipboardText");
            const clipboardText =
                typeof response.data === "string"
                    ? response.data
                    : (response.data?.data ?? "");

            if (!clipboardText) {
                return;
            }

            setURL(clipboardText);
            props.onChange(clipboardText);
            return;
        } catch (error) {
            console.error("Failed to get clipboard text:", error);
        }
    };

    const handleOpenInBrowser = () => {
        const normalizedUrl = url.trim();
        if (!normalizedUrl || normalizedUrl.startsWith("/book")) {
            return;
        }

        // Use the Bloom API to open the URL in the default browser
        post(`common/openUrl?url=${encodeURIComponent(normalizedUrl)}`);
    };

    const normalizedUrl = url.trim();
    const isOpenButtonDisabled =
        normalizedUrl.length === 0 || normalizedUrl.startsWith("/book");

    return (
        <Box
            css={css`
                display: flex;
                flex-direction: column;
                margin: 0;
            `}
        >
            <Typography css={headingStyle}>
                {urlHeading}
                <BloomTooltip tip={urlTooltip}>
                    <InfoOutlinedIcon
                        css={css`
                            font-size: 15px;
                            // put it vertically in line with the text
                            position: relative;
                            top: 2px;
                            margin-left: 4px;

                            color: ${kBloomBlue};
                        `}
                    />
                </BloomTooltip>
            </Typography>
            <Box
                css={css`
                    display: flex;
                    align-items: center;
                    gap: 8px;
                `}
            >
                <TextField
                    fullWidth
                    size="small"
                    value={url}
                    onChange={(e) => handleURLChange(e.target.value)}
                    placeholder={placeholderText}
                    variant="outlined"
                    css={css`
                        flex: 1;
                    `}
                    data-testid="url-input"
                />
                {/* More Menu */}
                <Box css={css``}>
                    <IconButton
                        onClick={handleMoreMenuClick}
                        size="small"
                        aria-label={optionsButtonLabel}
                        data-testid="url-editor-more-menu-button"
                        css={css`
                            color: ${kBloomBlue};
                        `}
                    >
                        <MoreHorizIcon fontSize="small" />
                    </IconButton>
                    <Menu
                        anchorEl={moreMenuAnchor}
                        open={Boolean(moreMenuAnchor)}
                        onClose={handleMoreMenuClose}
                        data-testid="url-editor-more-menu"
                    >
                        <MenuItem
                            onClick={handleBackMenuItemClick}
                            data-testid="url-editor-back-menu-item"
                            title={backMenuTitle}
                        >
                            {backMenuLabel}
                        </MenuItem>
                    </Menu>
                </Box>
                <BloomTooltip tip={pasteTooltip}>
                    <IconButton
                        onClick={handlePaste}
                        size="small"
                        css={css`
                            color: ${kBloomBlue};
                        `}
                        data-testid="paste-button"
                    >
                        <ContentPasteIcon />
                    </IconButton>
                </BloomTooltip>
                <BloomTooltip tip={openInBrowserTooltip}>
                    <IconButton
                        onClick={handleOpenInBrowser}
                        size="small"
                        disabled={isOpenButtonDisabled}
                        css={css`
                            color: ${kBloomBlue};
                            &:disabled {
                                color: rgba(0, 0, 0, 0.26);
                            }
                        `}
                        data-testid="open-button"
                    >
                        <OpenInNewIcon />
                    </IconButton>
                </BloomTooltip>
            </Box>
        </Box>
    );
};
