files:
  - source: /DistFiles/localization/en/*.xlf
    translation: /DistFiles/localization/%locale%/%original_file_name%
    languages_mapping:
      locale:
        es-ES: es
        pt-PT: pt
    update_option: update_as_unapproved
  - source: /DistFiles/localization/*/ReadMe-en.xlf
    translation: /%original_path%/ReadMe-%locale%.xlf
    languages_mapping:
      locale:
        es-ES: es
        pt-PT: pt
    update_option: update_as_unapproved
