files:
  - source: /DistFiles/localization/en/*.xlf
    translation: /DistFiles/localization/%two_letters_code%/%original_file_name%
  - source: /DistFiles/localization/*/ReadMe-en.xlf
    translation: /DistFiles/localization/%original_path%/ReadMe-%two_letters_code%.xlf
