files:
  - source: /DistFiles/localization/en/*.xlf
    translation: /DistFiles/localization/%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        zh-CN: zh-CN
    update_option: update_as_unapproved
  - source: /DistFiles/localization/*/ReadMe-en.xlf
    translation: /%original_path%/ReadMe-%two_letters_code%.xlf
    languages_mapping:
      two_letters_code:
        zh-CN: zh-CN
    update_option: update_as_unapproved
