import * as React from "react";
import { renderRoot } from "../../utils/reactRender";
import axios from "axios";
import { css } from "@emotion/react";
import Accordion from "@mui/material/Accordion";
import AccordionDetails from "@mui/material/AccordionDetails";
import AccordionSummary from "@mui/material/AccordionSummary";
import Typography from "@mui/material/Typography";
import { ThemeProvider } from "@mui/material/styles";
import { toolboxTheme } from "../../bloomMaterialUITheme";
import { LocalizedString } from "../../react_components/l10nComponents";
import {
    kBloomBlue,
    kBloomPanelBackground,
    kBloomUnselectedTabBackground,
} from "../../utils/colorUtils";
import { getMasterToolList } from "./toolbox";
import { setToolboxReactAdapter } from "./toolboxReactAdapter";
import { SubscriptionBadgeWithTooltipAndDialog } from "../../react_components/requiresSubscription";

// React host for the toolbox sidebar.
//
// This component bridges old and new toolbox systems while migration is in progress. It was generated by Copilot
// to allow the root of the toolbox to be rendered in React while still supporting several tools that have not yet
// been migrated to React. The goal is to eventually remove all legacy toolbox code and have a fully React-managed toolbox.
// The descriptions and plans below were also generated by Copilot and may or may not be helpful.
// - it renders accordion sections in React,
// - reuses already-instantiated legacy tool DOM when available,
// - and exposes a small adapter so legacy code can still control active tool state.
//
// Completed migration target:
// - React is the single owner of toolbox state and rendering,
// - each tool is rendered through a React component/factory (no legacy HTML injection),
// - no DOM adoption from legacy #toolbox roots,
// - no hydration polling or legacy add/remove bridge events,
// - and toolbox globals are reduced to a minimal compatibility surface (or removed).
//
// Practical completion checklist for this file:
// - remove existing legacy element adoption paths,
// - replace legacy event synchronization with direct React/store updates,
// - remove hidden legacy #toolbox root handling,
// - then simplify comments to describe a fully React-managed toolbox.

type ToolboxSection = {
    id: string;
    englishLabel: string;
    l10nKey: string;
    liveToolBodyElement?: HTMLDivElement;
};

const alwaysOnToolIds: string[] = ["talkingBook"];

const subscriptionToolIds = new Set<string>(["canvas", "motion", "music"]);

const toolIconPathByToolId: Record<string, string> = {
    talkingBook: "/bloom/images/microphone-white.svg",
    decodableReader: "/bloom/images/keys-white.png",
    leveledReader: "/bloom/images/steps-white.png",
    signLanguage: "/bloom/bookEdit/toolbox/signLanguage/signLanguageTool.svg",
    music: "/bloom/bookEdit/toolbox/music/music-notes-white.svg",
    motion: "/bloom/bookEdit/toolbox/motion/motion.svg",
    canvas: "/bloom/bookEdit/toolbox/canvas/Canvas%20Icon.svg",
    imageDescription:
        "/bloom/bookEdit/toolbox/imageDescription/ImageDescriptionToolIcon.svg",
    impairmentVisualizer:
        "/bloom/bookEdit/toolbox/impairmentVisualizer/blind-eye-white.svg",
};

const toolboxHeaderIconStyles = css`
    width: 16px;
    height: 16px;
    display: inline-block;
    background-position: center;
    background-repeat: no-repeat;
    background-size: contain;
    flex-shrink: 0;
`;

// Normalize mixed naming conventions (e.g., "canvas" vs "canvasTool") so
// React and legacy code can refer to the same logical tool.
const normalizeToolId = (toolId: string): string => {
    if (!toolId) {
        return toolId;
    }

    if (toolId.endsWith("Tool")) {
        return toolId.substring(0, toolId.length - 4);
    }

    return toolId;
};

// Convert normalized IDs back to the toolbox's traditional "*Tool" names when
// we need to notify legacy listeners.
const toToolboxToolId = (toolId: string): string => {
    if (!toolId) {
        return toolId;
    }
    if (toolId.endsWith("Tool") || toolId.endsWith("Visualizer")) {
        return toolId;
    }
    return `${toolId}Tool`;
};

const getToolboxLabelInfo = (
    toolId: string,
): { englishLabel: string; l10nKey: string } => {
    const normalizedToolId = normalizeToolId(toolId);
    if (normalizedToolId === "settings") {
        return {
            englishLabel: "More...",
            l10nKey: "EditTab.Toolbox.More",
        };
    }

    const toolIdUpper =
        normalizedToolId[0].toUpperCase() +
        normalizedToolId.substring(1, normalizedToolId.length);
    const englishBaseLabel = toolIdUpper.replace(/([A-Z])/g, " $1").trim();
    const endsWithVisualizer = normalizedToolId.endsWith("Visualizer");

    return {
        englishLabel: endsWithVisualizer
            ? englishBaseLabel
            : `${englishBaseLabel} Tool`,
        l10nKey: endsWithVisualizer
            ? `EditTab.Toolbox.${toolIdUpper}`
            : `EditTab.Toolbox.${toolIdUpper}Tool`,
    };
};

const sortToolIdsAlphabetically = (toolIds: string[]): string[] => {
    return [...toolIds].sort((a, b) =>
        getToolboxLabelInfo(a).englishLabel.localeCompare(
            getToolboxLabelInfo(b).englishLabel,
            undefined,
            {
                sensitivity: "base",
            },
        ),
    );
};

const makeSectionFromToolId = (toolId: string): ToolboxSection => {
    const labelInfo = getToolboxLabelInfo(toolId);
    return {
        id: toolId,
        englishLabel: labelInfo.englishLabel,
        l10nKey: labelInfo.l10nKey,
    };
};

const sortSectionsAlphabeticallyWithSettingsLast = (
    sections: ToolboxSection[],
): ToolboxSection[] => {
    const settingsSection = sections.find(
        (section) => section.id === "settings",
    );
    const nonSettingsSections = sections
        .filter((section) => section.id !== "settings")
        .sort((a, b) =>
            a.englishLabel.localeCompare(b.englishLabel, undefined, {
                sensitivity: "base",
            }),
        );

    if (!settingsSection) {
        return nonSettingsSections;
    }

    return [...nonSettingsSections, settingsSection];
};

const parseEnabledToolIds = (value: string): string[] => {
    const normalized = value
        .split(",")
        .map((toolId) => toolId.trim())
        .filter((toolId) => !!toolId)
        .map((toolId) => normalizeToolId(toolId));

    const toolIds = new Set<string>(normalized);
    alwaysOnToolIds.forEach((toolId) => toolIds.add(toolId));
    return Array.from(toolIds);
};

const buildSectionsFromEnabledToolIds = (
    enabledToolIds: string[],
): ToolboxSection[] => {
    const withMoreTabLast = sortToolIdsAlphabetically(
        enabledToolIds.filter((id) => id !== "settings"),
    );
    withMoreTabLast.push("settings");

    return sortSectionsAlphabeticallyWithSettingsLast(
        withMoreTabLast.map((toolId) => makeSectionFromToolId(toolId)),
    );
};

// Locate an existing legacy tool body element, checking both old and new data
// attribute spellings and both normalized/"*Tool" ID variants.
const getExistingToolboxContentElement = (
    toolId: string,
): HTMLDivElement | undefined => {
    const normalizedToolId = normalizeToolId(toolId);
    const candidateToolIds = new Set<string>([
        toolId,
        normalizedToolId,
        toToolboxToolId(toolId),
        toToolboxToolId(normalizedToolId),
    ]);

    for (const candidateToolId of candidateToolIds) {
        const contentElement = document.querySelector(
            `#toolbox > div[data-toolid='${candidateToolId}'], #toolbox > div[data-toolId='${candidateToolId}']`,
        ) as HTMLDivElement | null;
        if (contentElement) {
            return contentElement;
        }
    }

    return undefined;
};

const getLiveToolBodyElement = (toolId: string): HTMLDivElement | undefined => {
    // Use the element created by legacy beginAddTool() so we don't instantiate
    // a second React tool root and desynchronize tool state.
    return getExistingToolboxContentElement(toolId);
};

// This is part of the mess that Copilot made to allow the root of the toolbox to be
// rendered in React while still supporting several tools that have not yet been
// migrated to React. It was one of my first big refactors using CoPilot, and I should
// not have been so quick to just be glad it seemed to work. For some reason, its
// solution was to maintain an old jquery accordion in parallel with a new React
// implementation. Somehow, across these two versions of the toolbox that exist in
// parallel, a React tool can think it has a root element to render into, but it
// doesn't actually exist. Then we get stuck in a state where the tool's content
// is permanently replaced by a loading message. This function detects this
// situation and adjusts things so that the root element for the tool content
// gets created when needed.
// I don't think there's any good reason not to use the normal function declaration
// syntax except that Copilot seems to have done everything else in this file this way.
// I don't want to put a lot of effort into cleaning it up because I hope sometime soon
// we rework the remaining few non-React tools and can then get rid of the duplication
// and manage everything in normal React. I expect most of the code in this file to
// go away.
const ensureReactToolBodyElement = (
    toolId: string,
): HTMLDivElement | undefined => {
    const existing = getExistingToolboxContentElement(toolId);
    if (existing) {
        return existing;
    }

    const normalizedToolId = normalizeToolId(toolId);

    const tool = getMasterToolList().find((candidate) => {
        return candidate.id() === normalizedToolId;
    });
    if (!tool || !tool.makeRootElement) {
        return undefined;
    }

    const legacyToolboxRoot = document.getElementById("toolbox");
    if (!legacyToolboxRoot) {
        return undefined;
    }

    const fullToolId = toToolboxToolId(normalizedToolId);
    const content = tool.makeRootElement();
    content.setAttribute("data-toolId", fullToolId);

    const existingHeader = Array.from(legacyToolboxRoot.children).find(
        (child) => {
            return (
                child.tagName.toLowerCase() === "h3" &&
                child.getAttribute("data-toolId") === fullToolId
            );
        },
    ) as HTMLElement | undefined;
    if (!existingHeader) {
        const header = document.createElement("h3");
        header.setAttribute("data-toolId", fullToolId);
        legacyToolboxRoot.appendChild(header);
    }

    legacyToolboxRoot.appendChild(content);
    return content;
};

const getLegacyCurrentToolId = (): string | undefined => {
    const toolbox = window.toolboxBundle?.getTheOneToolbox?.();
    const currentTool = toolbox?.getCurrentTool?.();
    const currentToolId = currentTool?.id?.();
    if (!currentToolId) {
        return undefined;
    }

    return normalizeToolId(currentToolId);
};

// Hosts a legacy-owned DOM subtree inside React layout while preserving the
// original element instance (so tool state and event wiring stay intact).
const LiveToolBodyHost: React.FunctionComponent<{ element: HTMLDivElement }> = (
    props,
) => {
    const hostRef = React.useRef<HTMLDivElement | null>(null);

    const clearLegacyAccordionSizing = React.useCallback(
        (element: HTMLDivElement) => {
            element.style.height = "100%";
            element.style.width = "100%";
            element.style.minWidth = "0";
            element.style.flex = "1 1 auto";
            element.style.overflow = "";
            element.style.display = "block";
        },
        [],
    );

    React.useEffect(() => {
        const host = hostRef.current;
        if (!host) {
            return;
        }

        clearLegacyAccordionSizing(props.element);

        if (!host.contains(props.element)) {
            host.innerHTML = "";
            host.appendChild(props.element);
        }

        return () => {
            if (host.contains(props.element)) {
                host.removeChild(props.element);
            }
        };
    }, [props.element, clearLegacyAccordionSizing]);

    return (
        <div
            ref={hostRef}
            css={css`
                width: 100%;
                height: 100%;
                flex: 1;
                display: flex;
                flex-direction: column;
                align-items: stretch;
                min-height: 0;
                min-width: 0;
            `}
        ></div>
    );
};

// This component is the root of the whole toolbox sidebar. It is rendered into a dedicated
// host element created by the edit-frame page pug.
export const ToolboxRoot: React.FunctionComponent = () => {
    const [sections, setSections] = React.useState<ToolboxSection[]>([]);
    const [expandedSectionId, setExpandedSectionId] = React.useState<string>();
    const activeToolChangedCallbacks = React.useRef<
        ((toolId: string) => void)[]
    >([]);
    const hydratedToolIds = React.useRef<Set<string>>(new Set());

    // Resolve body content for a section.
    // Prefer a live legacy element to avoid duplicate tool roots; otherwise
    // ask the tool to make its React root.
    const hydrateToolBody = React.useCallback(async (toolId: string) => {
        if (hydratedToolIds.current.has(toolId)) {
            return;
        }

        hydratedToolIds.current.add(toolId);

        const liveToolBodyElement = getLiveToolBodyElement(toolId);
        if (liveToolBodyElement) {
            // Adopt the current live node from #toolbox so we don't create a duplicate
            // root for the same legacy tool.
            setSections((previousSections) =>
                previousSections.map((section) => {
                    if (section.id !== toolId) {
                        return section;
                    }
                    return {
                        ...section,
                        liveToolBodyElement,
                    };
                }),
            );
            return;
        }

        const createdReactToolBodyElement = ensureReactToolBodyElement(toolId);
        if (createdReactToolBodyElement) {
            setSections((previousSections) =>
                previousSections.map((section) => {
                    if (section.id !== toolId) {
                        return section;
                    }
                    return {
                        ...section,
                        liveToolBodyElement: createdReactToolBodyElement,
                    };
                }),
            );
            return;
        }

        hydratedToolIds.current.delete(toolId);
    }, []);

    // Load enabled toolbox tools and begin hydrating each section body.
    React.useEffect(() => {
        axios
            .get<string>("/bloom/api/toolbox/enabledTools")
            .then(async (response) => {
                const parsedIds = parseEnabledToolIds(response.data);
                const masterList = getMasterToolList();
                for (let i = parsedIds.length - 1; i >= 0; i--) {
                    const toolId = parsedIds[i];
                    if (!masterList.some((tool) => tool.id() === toolId)) {
                        parsedIds.splice(i, 1);
                    }
                }
                const builtSections =
                    buildSectionsFromEnabledToolIds(parsedIds);
                setSections(builtSections);
            })
            .catch((error) => {
                throw error;
            });
    }, [hydrateToolBody]);

    // Start hydration only after section state exists to avoid races where a tool
    // can be marked hydrated before there is any section to receive its body.
    React.useEffect(() => {
        sections.forEach((section) => {
            if (
                section.liveToolBodyElement ||
                hydratedToolIds.current.has(section.id)
            ) {
                return;
            }

            void hydrateToolBody(section.id);
        });
    }, [sections, hydrateToolBody]);

    // Keep unresolved sections hydrated over time because legacy tool roots are
    // not always available immediately when sections are first created (or recreated),
    // and there may be some possibility that they get removed by non-react code.
    // I don't fully understand why this is necessary, but in the early stages of
    // developing this wrapper, it happened quite often that a tool was opened and
    // nothing was there. This polling is defensive attempt to prevent that.
    // Once everything is fully in React, this should be unnecessary and can be removed.
    React.useEffect(() => {
        const intervalId = window.setInterval(() => {
            sections.forEach((section) => {
                const hasConnectedLiveToolBodyElement =
                    !!section.liveToolBodyElement &&
                    section.liveToolBodyElement.isConnected;

                if (hasConnectedLiveToolBodyElement) {
                    return;
                }

                if (
                    section.id === expandedSectionId &&
                    hydratedToolIds.current.has(section.id)
                ) {
                    // Forget that we hydrated the tool the user is looking at, so that
                    // hydrateToolBody() will actually try again to get it a body element.
                    hydratedToolIds.current.delete(section.id);
                }

                void hydrateToolBody(section.id);
            });
        }, 250);

        return () => {
            window.clearInterval(intervalId);
        };
    }, [sections, hydrateToolBody, expandedSectionId]);

    // Synchronize toolbox add/remove events from legacy code into React section
    // state so both systems reflect the same offered tools.
    React.useEffect(() => {
        const onToolAdded = (event: Event) => {
            const customEvent = event as CustomEvent<{ toolId: string }>;
            const addedToolId = normalizeToolId(customEvent.detail.toolId);

            setSections((previousSections) => {
                if (
                    previousSections.some(
                        (section) => section.id === addedToolId,
                    )
                ) {
                    return previousSections;
                }

                return sortSectionsAlphabeticallyWithSettingsLast([
                    ...previousSections,
                    makeSectionFromToolId(addedToolId),
                ]);
            });
        };

        const onToolRemoved = (event: Event) => {
            const customEvent = event as CustomEvent<{ toolId: string }>;
            const removedToolId = normalizeToolId(customEvent.detail.toolId);
            hydratedToolIds.current.delete(removedToolId);

            setSections((previousSections) => {
                const nextSections = previousSections.filter(
                    (section) => section.id !== removedToolId,
                );

                const firstSection = nextSections[0];
                // actually changes the expanded section only if the removed tool was the expanded one.
                // The awkward way of doing this is to guard against a stale value of expandedSectionId.
                setExpandedSectionId((previousExpandedSectionId) =>
                    previousExpandedSectionId === removedToolId
                        ? firstSection
                            ? firstSection.id
                            : undefined
                        : previousExpandedSectionId,
                );

                return nextSections;
            });
        };

        // These events get dispatched by legacy toolbox code when tools are added or removed
        //  from the legacy #toolbox container.
        window.addEventListener("toolbox-tool-added", onToolAdded);
        window.addEventListener("toolbox-tool-removed", onToolRemoved);

        return () => {
            window.removeEventListener("toolbox-tool-added", onToolAdded);
            window.removeEventListener("toolbox-tool-removed", onToolRemoved);
        };
    }, [hydrateToolBody]);

    // Expose activation adapter so legacy toolbox code can drive and observe React accordion state.
    React.useEffect(() => {
        if (!expandedSectionId) {
            const legacyCurrentToolId = getLegacyCurrentToolId();
            if (
                legacyCurrentToolId &&
                sections.some((section) => section.id === legacyCurrentToolId)
            ) {
                setExpandedSectionId(legacyCurrentToolId);
            }
        }

        // Register the adapter that the legacy toolbox code uses to drive and observe
        // which accordion section is active. See toolboxReactAdapter.ts.
        setToolboxReactAdapter({
            setActiveToolByToolId: (toolId: string) => {
                const normalizedToolId = normalizeToolId(toolId);
                setExpandedSectionId(normalizedToolId);
                const callbackToolId = toToolboxToolId(normalizedToolId);
                activeToolChangedCallbacks.current.forEach((callback) => {
                    callback(callbackToolId);
                });
            },
            onActiveToolChanged: (callback: (toolId: string) => void) => {
                activeToolChangedCallbacks.current.push(callback);
            },
        });
    }, [expandedSectionId, sections]);

    // The old jQuery toolbox logic still runs for now, and it calls .show() on #toolbox.
    // Keep that legacy root hidden so only the React root is visible.
    // (For now quite a lot of legacy code still uses the #toolbox root; it's even where
    // we get some of the tools which we move into the React accordion. So we can't just
    // remove it yet, though that's the long-term plan. For now just hide it.)
    React.useEffect(() => {
        const legacyToolboxElement = document.getElementById("toolbox");
        if (!legacyToolboxElement) {
            return;
        }

        const forceHideLegacyToolbox = () => {
            legacyToolboxElement.style.setProperty(
                "display",
                "none",
                "important",
            );
        };

        forceHideLegacyToolbox();

        const observer = new MutationObserver(() => {
            forceHideLegacyToolbox();
        });
        observer.observe(legacyToolboxElement, {
            attributes: true,
            attributeFilter: ["style", "class"],
        });

        return () => {
            observer.disconnect();
        };
    }, []);

    return (
        <div
            css={css`
                height: 100%;
                display: flex;
                flex-direction: column;
                // This overrides a font-size: x-small that is set on div.toolboxRoot
                // (it replaces something that we somehow inherited from a jquery stylesheet
                // in earlier versions of Bloom)
                font-size: 11px;
            `}
        >
            <ThemeProvider theme={toolboxTheme}>
                <div
                    css={css`
                        border-bottom: 1px solid rgba(255, 255, 255, 0.2);
                        background-color: ${kBloomPanelBackground};
                        display: flex;
                        flex-direction: column;
                        // Lets the darker panel background show through between the
                        // collapsed section headers, as it did in 6.3 and earlier (BL-16532).
                        gap: 1px;
                        height: 100%;
                        min-height: 0;

                        a {
                            color: white;
                        }

                        .helpLinkWrapper a {
                            color: white;
                        }
                    `}
                >
                    {sections.map((section) => (
                        <Accordion
                            key={section.id}
                            css={css`
                                background-color: ${kBloomUnselectedTabBackground};
                                color: white;
                                margin: 0;
                                display: flex;
                                flex-direction: column;
                                flex-shrink: 0;

                                &:before {
                                    display: none;
                                }

                                &.Mui-expanded {
                                    background-color: ${kBloomPanelBackground};
                                    flex: 1 1 auto;
                                    min-height: 0;
                                }

                                &.Mui-expanded > .MuiCollapse-root {
                                    display: flex;
                                    flex-direction: column;
                                    flex: 1;
                                    min-height: 0;
                                    overflow: hidden;
                                }

                                &.Mui-expanded
                                    > .MuiCollapse-root
                                    > .MuiCollapse-wrapper,
                                &.Mui-expanded
                                    > .MuiCollapse-root
                                    > .MuiCollapse-wrapper
                                    > .MuiCollapse-wrapperInner,
                                &.Mui-expanded
                                    > .MuiCollapse-root
                                    > .MuiCollapse-wrapper
                                    > .MuiCollapse-wrapperInner
                                    > .MuiAccordion-region {
                                    display: flex;
                                    flex-direction: column;
                                    flex: 1;
                                    min-height: 0;
                                    overflow: hidden;
                                }
                            `}
                            disableGutters
                            expanded={expandedSectionId === section.id}
                            onChange={(_event, expanded) => {
                                const nextSectionId = expanded
                                    ? section.id
                                    : undefined;
                                setExpandedSectionId(nextSectionId);
                                if (nextSectionId) {
                                    const toolId =
                                        toToolboxToolId(nextSectionId);
                                    activeToolChangedCallbacks.current.forEach(
                                        (callback) => {
                                            callback(toolId);
                                        },
                                    );
                                }
                            }}
                        >
                            <AccordionSummary
                                css={css`
                                    min-height: 32px;
                                    padding-left: 5px;
                                    padding-right: 12px;

                                    & .MuiAccordionSummary-content {
                                        margin: 8px 0;
                                        display: flex;
                                        align-items: center;
                                        gap: 12px;
                                    }

                                    &.Mui-expanded {
                                        min-height: 32px;
                                        background-color: ${kBloomBlue};
                                    }
                                `}
                            >
                                <span
                                    css={
                                        section.id === "talkingBook"
                                            ? [
                                                  toolboxHeaderIconStyles,
                                                  css`
                                                      width: 12px;
                                                      background-size: 12px 16px;
                                                  `,
                                              ]
                                            : toolboxHeaderIconStyles
                                    }
                                    data-toolid={section.id}
                                    style={{
                                        backgroundImage: `url(${toolIconPathByToolId[section.id] || ""})`,
                                    }}
                                ></span>
                                <Typography
                                    css={css`
                                        flex-grow: 1;
                                        font-size: 11px;
                                    `}
                                >
                                    <LocalizedString l10nKey={section.l10nKey}>
                                        {section.englishLabel}
                                    </LocalizedString>
                                </Typography>
                                {subscriptionToolIds.has(section.id) && (
                                    <span>
                                        <SubscriptionBadgeWithTooltipAndDialog
                                            featureName={section.id}
                                        />
                                    </span>
                                )}
                            </AccordionSummary>
                            <AccordionDetails
                                css={css`
                                    background-color: ${kBloomPanelBackground};
                                    padding: 0;
                                    flex: 1;
                                    display: flex;
                                    min-height: 0;
                                    overflow: auto;
                                `}
                            >
                                <div
                                    css={css`
                                        width: 100%;
                                        display: flex;
                                        flex-direction: column;
                                        align-items: stretch;
                                        min-height: 100%;
                                        overflow: visible;

                                        div[data-toolid="leveledReaderTool"],
                                        div[data-toolId="decodableReaderTool"] {
                                            width: 100% !important;
                                            min-width: 0;
                                            align-self: stretch !important;
                                            display: block !important;
                                            box-sizing: border-box;
                                            margin-right: 0 !important;
                                            padding-right: 0 !important;
                                        }

                                        // The Decodable/Leveled reader tool bodies are
                                        // adopted from the old jQuery-UI accordion and
                                        // still wear its header classes (ui-accordion-header,
                                        // ui-state-default) plus jQuery hover/focus handlers
                                        // that add ui-state-hover/-focus. Here they are tool
                                        // *bodies*, not headers, so that theming is wrong: left
                                        // alone, hovering an opened reader tool paints its whole
                                        // body the jQuery-UI "hover" lightcoral (#f08080).
                                        // Neutralize the stray header theming. (BL-16501)
                                        div[data-toolid].ui-accordion-header {
                                            &,
                                            &.ui-state-hover,
                                            &.ui-state-focus,
                                            &.ui-state-active {
                                                background: transparent !important;
                                                border: none !important;
                                                font-weight: normal;
                                            }
                                        }

                                        // Those same adopted bodies also keep the
                                        // header icon jQuery-UI's _createIcons()
                                        // prepends to every header: a
                                        // ui-icon-triangle-1-e sprite. As a body
                                        // (not a header) it renders as a stray
                                        // right-pointing arrowhead in the top-left
                                        // corner. The rule above only neutralized the
                                        // header background/border, not this child
                                        // icon, so hide it too. (BL-16538)
                                        div[data-toolid]
                                            span.ui-accordion-header-icon {
                                            display: none !important;
                                        }
                                    `}
                                >
                                    {section.liveToolBodyElement ? (
                                        <LiveToolBodyHost
                                            element={
                                                section.liveToolBodyElement
                                            }
                                        />
                                    ) : (
                                        <Typography>
                                            Loading {section.englishLabel}...
                                        </Typography>
                                    )}
                                </div>
                            </AccordionDetails>
                        </Accordion>
                    ))}
                </div>
            </ThemeProvider>
            <div
                id="toolbox"
                css={css`
                    display: none;
                `}
            ></div>
        </div>
    );
};

export const renderToolboxRoot = (): void => {
    // Bootstraps the React toolbox into the dedicated host element created by
    // the edit-frame page markup.
    const hostElement = document.getElementById("toolbox-react-root");
    if (!hostElement) {
        return;
    }

    hostElement.style.height = "100%";
    hostElement.style.display = "flex";
    hostElement.style.flexDirection = "column";

    renderRoot(<ToolboxRoot />, hostElement);
};
