import * as React from "react";
import * as ReactDOM from "react-dom";
import axios from "axios";
import { css } from "@emotion/react";
import Accordion from "@mui/material/Accordion";
import AccordionDetails from "@mui/material/AccordionDetails";
import AccordionSummary from "@mui/material/AccordionSummary";
import Typography from "@mui/material/Typography";
import { ThemeProvider } from "@mui/material/styles";
import { toolboxTheme } from "../../bloomMaterialUITheme";
import {
    kBloomBlue,
    kBloomPanelBackground,
    kBloomUnselectedTabBackground,
} from "../../utils/colorUtils";

// React host for the toolbox sidebar.
//
// This component bridges old and new toolbox systems while migration is in progress. It was generated by Copilot
// to allow the root of the toolbox to be rendered in React while still supporting several tools that have not yet
// been migrated to React. The goal is to eventually remove all legacy toolbox code and have a fully React-managed toolbox.
// The descriptions and plans below were also generated by Copilot and may or may not be helpful.
// - it renders accordion sections in React,
// - reuses already-instantiated legacy tool DOM when available,
// - falls back to loading legacy HTML snippets when live DOM is not ready,
// - and exposes a small adapter so legacy code can still control active tool state.
//
// Completed migration target:
// - React is the single owner of toolbox state and rendering,
// - each tool is rendered through a React component/factory (no legacy HTML injection),
// - no DOM adoption from legacy #toolbox roots,
// - no hydration polling or legacy add/remove bridge events,
// - and toolbox globals are reduced to a minimal compatibility surface (or removed).
//
// Practical completion checklist for this file:
// - remove legacy HTML fallback loading/injection paths,
// - remove existing legacy element adoption paths,
// - replace legacy event synchronization with direct React/store updates,
// - remove hidden legacy #toolbox root handling,
// - then simplify comments to describe a fully React-managed toolbox.

type ToolboxSection = {
    id: string;
    label: string;
    legacyToolHtmlSubPath?: string;
    legacyToolBodyHtml?: string;
    liveToolBodyElement?: HTMLDivElement;
};

const alwaysOnToolIds: string[] = ["talkingBook"];

const subscriptionToolIds = new Set<string>(["canvas", "motion", "music"]);

const toolIconPathByToolId: Record<string, string> = {
    talkingBook: "/bloom/images/microphone-white.svg",
    decodableReader: "/bloom/images/keys-white.png",
    leveledReader: "/bloom/images/steps-white.png",
    signLanguage: "/bloom/bookEdit/toolbox/signLanguage/signLanguageTool.svg",
    music: "/bloom/bookEdit/toolbox/music/music-notes-white.svg",
    motion: "/bloom/bookEdit/toolbox/motion/motion.svg",
    canvas: "/bloom/bookEdit/toolbox/canvas/Canvas%20Icon.svg",
    imageDescription:
        "/bloom/bookEdit/toolbox/imageDescription/ImageDescriptionToolIcon.svg",
    impairmentVisualizer:
        "/bloom/bookEdit/toolbox/impairmentVisualizer/blind-eye-white.svg",
};

const legacyToolSubPathByToolId: Record<string, string> = {
    talkingBook: "talkingBook/talkingBookToolboxTool.html",
    decodableReader: "readers/decodableReader/decodableReaderToolboxTool.html",
    leveledReader: "readers/leveledReader/leveledReaderToolboxTool.html",
    settings: "settings/Settings.html",
    settingsTool: "settings/Settings.html",
};

const toolboxHeaderIconStyles = css`
    width: 16px;
    height: 16px;
    display: inline-block;
    background-position: center;
    background-repeat: no-repeat;
    background-size: contain;
    flex-shrink: 0;
`;

// Normalize mixed naming conventions (e.g., "canvas" vs "canvasTool") so
// React and legacy code can refer to the same logical tool.
const normalizeToolId = (toolId: string): string => {
    if (!toolId) {
        return toolId;
    }

    if (toolId.endsWith("Tool")) {
        return toolId.substring(0, toolId.length - 4);
    }

    return toolId;
};

// Convert normalized IDs back to the toolbox's traditional "*Tool" names when
// we need to notify legacy listeners.
const toToolboxToolId = (toolId: string): string => {
    if (!toolId) {
        return toolId;
    }
    if (toolId.endsWith("Tool") || toolId.endsWith("Visualizer")) {
        return toolId;
    }
    return `${toolId}Tool`;
};

const makeLabelFromToolId = (toolId: string): string => {
    if (toolId === "settings") {
        return "More...";
    }

    return toolId
        .replace(/Tool$/, "")
        .replace(/([A-Z])/g, " $1")
        .trim()
        .replace(/^./, (c) => c.toUpperCase());
};

const sortToolIdsAlphabetically = (toolIds: string[]): string[] => {
    return [...toolIds].sort((a, b) =>
        makeLabelFromToolId(a).localeCompare(
            makeLabelFromToolId(b),
            undefined,
            {
                sensitivity: "base",
            },
        ),
    );
};

const makeSectionFromToolId = (toolId: string): ToolboxSection => {
    return {
        id: toolId,
        label: makeLabelFromToolId(toolId),
        legacyToolHtmlSubPath: legacyToolSubPathByToolId[toolId],
    };
};

const sortSectionsAlphabeticallyWithSettingsLast = (
    sections: ToolboxSection[],
): ToolboxSection[] => {
    const settingsSection = sections.find(
        (section) => section.id === "settings",
    );
    const nonSettingsSections = sections
        .filter((section) => section.id !== "settings")
        .sort((a, b) =>
            a.label.localeCompare(b.label, undefined, {
                sensitivity: "base",
            }),
        );

    if (!settingsSection) {
        return nonSettingsSections;
    }

    return [...nonSettingsSections, settingsSection];
};

const parseEnabledToolIds = (value: string): string[] => {
    const normalized = value
        .split(",")
        .map((toolId) => toolId.trim())
        .filter((toolId) => !!toolId)
        .map((toolId) => normalizeToolId(toolId));

    const toolIds = new Set<string>(normalized);
    alwaysOnToolIds.forEach((toolId) => toolIds.add(toolId));
    return Array.from(toolIds);
};

const buildSectionsFromEnabledToolIds = (
    enabledToolIds: string[],
): ToolboxSection[] => {
    const withMoreTabLast = sortToolIdsAlphabetically(
        enabledToolIds.filter((id) => id !== "settings"),
    );
    withMoreTabLast.push("settings");

    return sortSectionsAlphabeticallyWithSettingsLast(
        withMoreTabLast.map((toolId) => makeSectionFromToolId(toolId)),
    );
};

// Locate an existing legacy tool body element, checking both old and new data
// attribute spellings and both normalized/"*Tool" ID variants.
const getExistingToolboxContentElement = (
    toolId: string,
): HTMLDivElement | undefined => {
    const normalizedToolId = normalizeToolId(toolId);
    const candidateToolIds = new Set<string>([
        toolId,
        normalizedToolId,
        toToolboxToolId(toolId),
        toToolboxToolId(normalizedToolId),
    ]);

    for (const candidateToolId of candidateToolIds) {
        const contentElement = document.querySelector(
            `#toolbox > div[data-toolid='${candidateToolId}'], #toolbox > div[data-toolId='${candidateToolId}']`,
        ) as HTMLDivElement | null;
        if (contentElement) {
            return contentElement;
        }
    }

    return undefined;
};

const getLiveToolBodyElement = (toolId: string): HTMLDivElement | undefined => {
    // Use the element created by legacy beginAddTool() so we don't instantiate
    // a second React tool root and desynchronize tool state.
    return getExistingToolboxContentElement(toolId);
};

const getLegacyCurrentToolId = (): string | undefined => {
    const toolbox = window.toolboxBundle?.getTheOneToolbox?.();
    const currentTool = toolbox?.getCurrentTool?.();
    const currentToolId = currentTool?.id?.();
    if (!currentToolId) {
        return undefined;
    }

    return normalizeToolId(currentToolId);
};

// Hosts a legacy-owned DOM subtree inside React layout while preserving the
// original element instance (so tool state and event wiring stay intact).
const LiveToolBodyHost: React.FunctionComponent<{ element: HTMLDivElement }> = (
    props,
) => {
    const hostRef = React.useRef<HTMLDivElement | null>(null);

    const clearLegacyAccordionSizing = React.useCallback(
        (element: HTMLDivElement) => {
            element.style.height = "100%";
            element.style.width = "100%";
            element.style.minWidth = "0";
            element.style.flex = "1 1 auto";
            element.style.overflow = "";
            element.style.display = "block";
        },
        [],
    );

    React.useEffect(() => {
        const host = hostRef.current;
        if (!host) {
            return;
        }

        clearLegacyAccordionSizing(props.element);

        if (!host.contains(props.element)) {
            host.innerHTML = "";
            host.appendChild(props.element);
        }

        return () => {
            if (host.contains(props.element)) {
                host.removeChild(props.element);
            }
        };
    }, [props.element, clearLegacyAccordionSizing]);

    return (
        <div
            ref={hostRef}
            css={css`
                width: 100%;
                height: 100%;
                flex: 1;
                display: flex;
                flex-direction: column;
                align-items: stretch;
                min-height: 0;
                min-width: 0;
            `}
        ></div>
    );
};
// Legacy toolbox HTML files contain wrappers and scripts; for React rendering we
// only inject the first meaningful tool-body div.
const extractFirstToolContentDivAsHtml = (rawHtml: string): string => {
    const parsedDocument = new DOMParser().parseFromString(
        rawHtml,
        "text/html",
    );
    const topLevelElements = Array.from(parsedDocument.body.children);
    const firstTopLevelDiv = topLevelElements.find(
        (element) => element.tagName.toLowerCase() === "div",
    );
    if (firstTopLevelDiv) {
        return firstTopLevelDiv.outerHTML;
    }

    const firstAnyDiv = parsedDocument.body.querySelector("div");
    if (firstAnyDiv) {
        return firstAnyDiv.outerHTML;
    }

    throw new Error("Legacy toolbox html did not contain a div tool body.");
};

const loadLegacyToolBodyHtml = async (
    section: ToolboxSection,
): Promise<string | undefined> => {
    if (!section.legacyToolHtmlSubPath) {
        return undefined;
    }

    const response = await axios.get<string>(
        `/bloom/bookEdit/toolbox/${section.legacyToolHtmlSubPath}`,
    );
    return extractFirstToolContentDivAsHtml(response.data);
};

// This component is the root of the whole toolbox sidebar. It is rendered into a dedicated
// host element created by the edit-frame page pug.
export const ToolboxRoot: React.FunctionComponent = () => {
    const [sections, setSections] = React.useState<ToolboxSection[]>([]);
    const [expandedSectionId, setExpandedSectionId] = React.useState<string>();
    const activeToolChangedCallbacks = React.useRef<
        ((toolId: string) => void)[]
    >([]);
    const hydratedToolIds = React.useRef<Set<string>>(new Set());

    // Resolve body content for a section.
    // Prefer a live legacy element to avoid duplicate tool roots; otherwise
    // load static legacy HTML as a temporary fallback.
    const hydrateToolBody = React.useCallback(async (toolId: string) => {
        if (hydratedToolIds.current.has(toolId)) {
            return;
        }

        const liveToolBodyElement = getLiveToolBodyElement(toolId);
        if (liveToolBodyElement) {
            // Adopt the current live node from #toolbox so we don't create a duplicate
            // root for the same legacy tool.
            hydratedToolIds.current.add(toolId);
            setSections((previousSections) =>
                previousSections.map((section) =>
                    section.id === toolId
                        ? {
                              ...section,
                              liveToolBodyElement,
                          }
                        : section,
                ),
            );
            return;
        }

        const legacyToolHtmlSubPath = legacyToolSubPathByToolId[toolId];
        if (legacyToolHtmlSubPath) {
            try {
                const legacyToolBodyHtml = await loadLegacyToolBodyHtml({
                    id: toolId,
                    label: "",
                    legacyToolHtmlSubPath,
                });
                hydratedToolIds.current.add(toolId);
                setSections((previousSections) =>
                    previousSections.map((section) =>
                        section.id === toolId
                            ? {
                                  ...section,
                                  legacyToolBodyHtml,
                              }
                            : section,
                    ),
                );
            } catch (error) {
                console.error(
                    `Failed to load legacy toolbox HTML for ${toolId}.`,
                    error,
                );
            }
            return;
        }
    }, []);

    // Load enabled toolbox tools and begin hydrating each section body.
    React.useEffect(() => {
        axios
            .get<string>("/bloom/api/toolbox/enabledTools")
            .then(async (response) => {
                const parsedIds = parseEnabledToolIds(response.data);
                const builtSections =
                    buildSectionsFromEnabledToolIds(parsedIds);
                setSections(builtSections);
                builtSections.forEach((section) => {
                    void hydrateToolBody(section.id);
                });
            })
            .catch((error) => {
                throw error;
            });
    }, [hydrateToolBody]);

    // Some tool content elements may appear shortly after we build sections.
    // Keep trying unresolved live tools until their existing DOM is available.
    React.useEffect(() => {
        // To avoid unnecessary re-renders, only update sections when we actually find a new live element.
        setSections((previousSections) => {
            let changed = false;
            const nextSections = previousSections.map((section) => {
                // If it's not legacy, we don't need to 'hydrate' it (look for the body in the legacy accordion).
                // If it already has a live element, we don't need to look for it again.
                // So such sections just copy into the new array unchanged.
                if (
                    !section.legacyToolBodyHtml ||
                    section.liveToolBodyElement
                ) {
                    return section;
                }

                // If we still don't have a live element, keep the one that is waiting to be hydrated.
                const liveToolBodyElement = getLiveToolBodyElement(section.id);
                if (!liveToolBodyElement) {
                    return section;
                }

                changed = true;
                hydratedToolIds.current.add(section.id);
                return {
                    ...section,
                    liveToolBodyElement,
                    legacyToolBodyHtml: undefined,
                };
            });

            // If we didn't change anything, return the old array so React doesn't re-render unnecessarily.
            return changed ? nextSections : previousSections;
        });
    }, [sections]);

    // If a previously adopted live node is no longer connected, clear our reference
    // so later hydration can look for a replacement node under #toolbox.
    // Note: getLiveToolBodyElement() cannot rediscover the same detached element; it
    // only finds currently attached nodes in the legacy toolbox container.
    React.useEffect(() => {
        setSections((previousSections) => {
            let changed = false;
            const disconnectedToolIds: string[] = [];
            // Similar logic so that only if we actually find a newly disconnected element
            // do we return a different object and cause a re-render.
            const nextSections = previousSections.map((section) => {
                if (
                    !section.liveToolBodyElement ||
                    section.liveToolBodyElement.isConnected
                ) {
                    return section;
                }

                changed = true;
                disconnectedToolIds.push(section.id);
                return {
                    ...section,
                    liveToolBodyElement: undefined,
                };
            });

            disconnectedToolIds.forEach((toolId) => {
                hydratedToolIds.current.delete(toolId);
            });

            return changed ? nextSections : previousSections;
        });
    }, [sections]);

    // Keep unresolved sections hydrated over time because legacy tool roots are
    // not always available immediately when sections are first created (or recreated),
    // and there may be some possibility that they get removed by non-react code.
    // I don't fully understand why this is necessary, but in the early stages of
    // developing this wrapper, it happened quite often that a tool was opened and
    // nothing was there. This polling is defensive attempt to prevent that.
    // Once everything is fully in React, this should be unnecessary and can be removed.
    React.useEffect(() => {
        const intervalId = window.setInterval(() => {
            sections.forEach((section) => {
                const hasBodyContent =
                    !!section.legacyToolBodyHtml ||
                    !!section.liveToolBodyElement;

                if (hasBodyContent) {
                    return;
                }

                if (
                    section.id === expandedSectionId &&
                    hydratedToolIds.current.has(section.id)
                ) {
                    hydratedToolIds.current.delete(section.id);
                }

                if (!hydratedToolIds.current.has(section.id)) {
                    void hydrateToolBody(section.id);
                }
            });
        }, 250);

        return () => {
            window.clearInterval(intervalId);
        };
    }, [sections, hydrateToolBody, expandedSectionId]);

    // Synchronize toolbox add/remove events from legacy code into React section
    // state so both systems reflect the same offered tools.
    React.useEffect(() => {
        const onToolAdded = (event: Event) => {
            const customEvent = event as CustomEvent<{ toolId: string }>;
            const addedToolId = normalizeToolId(customEvent.detail.toolId);

            setSections((previousSections) => {
                if (
                    previousSections.some(
                        (section) => section.id === addedToolId,
                    )
                ) {
                    return previousSections;
                }

                return sortSectionsAlphabeticallyWithSettingsLast([
                    ...previousSections,
                    makeSectionFromToolId(addedToolId),
                ]);
            });

            void hydrateToolBody(addedToolId);
        };

        const onToolRemoved = (event: Event) => {
            const customEvent = event as CustomEvent<{ toolId: string }>;
            const removedToolId = normalizeToolId(customEvent.detail.toolId);
            hydratedToolIds.current.delete(removedToolId);

            setSections((previousSections) => {
                const nextSections = previousSections.filter(
                    (section) => section.id !== removedToolId,
                );

                const firstSection = nextSections[0];
                // actually changes the expanded section only if the removed tool was the expanded one.
                // The awkward way of doing this is to guard against a stale value of expandedSectionId.
                setExpandedSectionId((previousExpandedSectionId) =>
                    previousExpandedSectionId === removedToolId
                        ? firstSection
                            ? firstSection.id
                            : undefined
                        : previousExpandedSectionId,
                );

                return nextSections;
            });
        };

        // These events get dispatched by legacy toolbox code when tools are added or removed
        //  from the legacy #toolbox container.
        window.addEventListener("toolbox-tool-added", onToolAdded);
        window.addEventListener("toolbox-tool-removed", onToolRemoved);

        return () => {
            window.removeEventListener("toolbox-tool-added", onToolAdded);
            window.removeEventListener("toolbox-tool-removed", onToolRemoved);
        };
    }, [hydrateToolBody]);

    // Expose activation adapter so legacy toolbox code can drive and observe React accordion state.
    React.useEffect(() => {
        if (!expandedSectionId) {
            const legacyCurrentToolId = getLegacyCurrentToolId();
            if (
                legacyCurrentToolId &&
                sections.some((section) => section.id === legacyCurrentToolId)
            ) {
                setExpandedSectionId(legacyCurrentToolId);
            }
        }

        // We expose this adapter on the window so legacy code which may not even be useing module syntax
        // can use it. We can change it to an export when all tools are modules, and get rid of it when
        // all tools are React components.
        window.toolboxReactAdapter = {
            isEnabled: () => true,
            setActiveToolByToolId: (toolId: string) => {
                setExpandedSectionId(normalizeToolId(toolId));
            },
            getActiveToolId: () => {
                if (!expandedSectionId) {
                    return undefined;
                }
                return toToolboxToolId(expandedSectionId);
            },
            onActiveToolChanged: (callback: (toolId: string) => void) => {
                activeToolChangedCallbacks.current.push(callback);
            },
        };
    }, [expandedSectionId, sections]);

    // The old jQuery toolbox logic still runs for now, and it calls .show() on #toolbox.
    // Keep that legacy root hidden so only the React root is visible.
    // (For now quite a lot of legacy code still uses the #toolbox root; it's even where
    // we get some of the tools which we move into the React accordion. So we can't just
    // remove it yet, though that's the long-term plan. For now just hide it.)
    React.useEffect(() => {
        const legacyToolboxElement = document.getElementById("toolbox");
        if (!legacyToolboxElement) {
            return;
        }

        const forceHideLegacyToolbox = () => {
            legacyToolboxElement.style.setProperty(
                "display",
                "none",
                "important",
            );
        };

        forceHideLegacyToolbox();

        const observer = new MutationObserver(() => {
            forceHideLegacyToolbox();
        });
        observer.observe(legacyToolboxElement, {
            attributes: true,
            attributeFilter: ["style", "class"],
        });

        return () => {
            observer.disconnect();
        };
    }, []);

    return (
        <div
            css={css`
                height: 100%;
                display: flex;
                flex-direction: column;
            `}
        >
            <ThemeProvider theme={toolboxTheme}>
                <div
                    css={css`
                        border-bottom: 1px solid rgba(255, 255, 255, 0.2);
                        background-color: ${kBloomPanelBackground};
                        display: flex;
                        flex-direction: column;
                        height: 100%;
                        min-height: 0;

                        a {
                            color: white;
                        }

                        .helpLinkWrapper a {
                            color: white;
                        }
                    `}
                >
                    {sections.map((section) => (
                        <Accordion
                            key={section.id}
                            css={css`
                                background-color: ${kBloomUnselectedTabBackground};
                                color: white;
                                margin: 0;
                                display: flex;
                                flex-direction: column;
                                flex-shrink: 0;

                                &:before {
                                    display: none;
                                }

                                &.Mui-expanded {
                                    background-color: ${kBloomPanelBackground};
                                    flex: 1 1 auto;
                                    min-height: 0;
                                }

                                &.Mui-expanded > .MuiCollapse-root {
                                    display: flex;
                                    flex-direction: column;
                                    flex: 1;
                                    min-height: 0;
                                    overflow: hidden;
                                }

                                &.Mui-expanded
                                    > .MuiCollapse-root
                                    > .MuiCollapse-wrapper,
                                &.Mui-expanded
                                    > .MuiCollapse-root
                                    > .MuiCollapse-wrapper
                                    > .MuiCollapse-wrapperInner,
                                &.Mui-expanded
                                    > .MuiCollapse-root
                                    > .MuiCollapse-wrapper
                                    > .MuiCollapse-wrapperInner
                                    > .MuiAccordion-region {
                                    display: flex;
                                    flex-direction: column;
                                    flex: 1;
                                    min-height: 0;
                                    overflow: hidden;
                                }
                            `}
                            disableGutters
                            expanded={expandedSectionId === section.id}
                            onChange={(_event, expanded) => {
                                const nextSectionId = expanded
                                    ? section.id
                                    : undefined;
                                setExpandedSectionId(nextSectionId);
                                if (nextSectionId) {
                                    const toolId =
                                        toToolboxToolId(nextSectionId);
                                    activeToolChangedCallbacks.current.forEach(
                                        (callback) => {
                                            callback(toolId);
                                        },
                                    );
                                }
                            }}
                        >
                            <AccordionSummary
                                css={css`
                                    min-height: 32px;
                                    padding-left: 5px;
                                    padding-right: 12px;

                                    & .MuiAccordionSummary-content {
                                        margin: 8px 0;
                                        display: flex;
                                        align-items: center;
                                        gap: 12px;
                                    }

                                    &.Mui-expanded {
                                        min-height: 32px;
                                        background-color: ${kBloomBlue};
                                    }
                                `}
                            >
                                <span
                                    css={
                                        section.id === "talkingBook"
                                            ? [
                                                  toolboxHeaderIconStyles,
                                                  css`
                                                      width: 12px;
                                                      background-size: 12px 16px;
                                                  `,
                                              ]
                                            : toolboxHeaderIconStyles
                                    }
                                    data-toolid={section.id}
                                    style={{
                                        backgroundImage: `url(${toolIconPathByToolId[section.id] || ""})`,
                                    }}
                                ></span>
                                <Typography
                                    css={css`
                                        flex-grow: 1;
                                    `}
                                >
                                    {section.label}
                                </Typography>
                                {subscriptionToolIds.has(section.id) && (
                                    <span className="subscription-badge"></span>
                                )}
                            </AccordionSummary>
                            <AccordionDetails
                                css={css`
                                    background-color: ${kBloomPanelBackground};
                                    padding: 0;
                                    flex: 1;
                                    display: flex;
                                    min-height: 0;
                                    overflow: auto;
                                `}
                            >
                                <div
                                    css={css`
                                        width: 100%;
                                        display: flex;
                                        flex-direction: column;
                                        align-items: stretch;
                                        min-height: 100%;
                                        overflow: visible;

                                        #leveled-reader-tool-content,
                                        #decodable-reader-tool-content {
                                            width: 100% !important;
                                            box-sizing: border-box;
                                            min-width: 0;
                                            display: block !important;
                                            align-self: stretch;
                                            margin-right: 0 !important;
                                            padding-right: 0 !important;
                                        }

                                        > div[data-toolid="leveledReaderTool"],
                                        > div[data-toolid="decodableReaderTool"],
                                        > div[data-toolId="leveledReaderTool"],
                                        > div[data-toolId="decodableReaderTool"] {
                                            width: 100% !important;
                                            min-width: 0;
                                            align-self: stretch !important;
                                            display: block !important;
                                            box-sizing: border-box;
                                            margin-right: 0 !important;
                                            padding-right: 0 !important;
                                        }
                                    `}
                                >
                                    {section.liveToolBodyElement ? (
                                        <LiveToolBodyHost
                                            element={
                                                section.liveToolBodyElement
                                            }
                                        />
                                    ) : section.legacyToolBodyHtml ? (
                                        <div
                                            css={css`
                                                width: 100%;
                                                min-height: 100%;
                                                display: flex;
                                                flex-direction: column;
                                            `}
                                            dangerouslySetInnerHTML={{
                                                __html: section.legacyToolBodyHtml,
                                            }}
                                        ></div>
                                    ) : (
                                        <Typography>
                                            Loading {section.label}...
                                        </Typography>
                                    )}
                                </div>
                            </AccordionDetails>
                        </Accordion>
                    ))}
                </div>
            </ThemeProvider>
            <div
                id="toolbox"
                css={css`
                    display: none;
                `}
            ></div>
        </div>
    );
};

export const renderToolboxRoot = (): void => {
    // Bootstraps the React toolbox into the dedicated host element created by
    // the edit-frame page markup.
    const hostElement = document.getElementById("toolbox-react-root");
    if (!hostElement) {
        return;
    }

    hostElement.style.height = "100%";
    hostElement.style.display = "flex";
    hostElement.style.flexDirection = "column";

    ReactDOM.render(<ToolboxRoot />, hostElement);
};
